### ISSUE TITLE
Windows package not uploaded to anaconda's conda-forge channel after merging PR

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/freeglut-feedstock#10]
PR was merged [19 days ago](https://github.com/conda-forge/freeglut-feedstock/pull/2#event-799469757).

**Comment by jakirkham** [comment]
@pelson , any ideas why this might have happened? AFAICT the builds completed successfully, but the upload never occurred. Could you please double check that are token is correct? Is there anything else you could think of that might be wrong?

**Comment by shadowwalkersb** [comment]
Still no freeglut Windows packages on conda-forge.

**Comment by jakirkham** [comment]
Indeed. Please see these [logs]( https://ci.appveyor.com/project/conda-forge/freeglut-feedstock/branch/master ).

**Comment by jakirkham** [comment]
Indeed. Please see these [logs]( https://ci.appveyor.com/project/conda-forge/freeglut-feedstock/build/1.0.30 ).

**Comment by shadowwalkersb** [comment]
> Indeed. Please see these logs.

Yup. Nice puzzle...

**Comment by shadowwalkersb** [comment]
Can [this](https://github.com/conda-forge/freeglut-feedstock/commit/b3b6aabd5e13de935b5476574c50a5b564c7a30b) have anything to do with the problem?

**Comment by shadowwalkersb** [comment]
Submitted a PR ( https://github.com/conda-forge/freeglut-feedstock/pull/12 ) reverting commit b3b6aabd5e13de935b5476574c50a5b564c7a30b.

**Comment by jakirkham** [comment]
Yes, that looks like the culprit. Must have missed it. SGTM

**Comment by shadowwalkersb** [comment]
Probably, a nooby mistake? :-)

**Comment by jakirkham** [comment]
Or a reviewer mistake. Sorry. 😞

In any event, it looks like we may have it sorted out.

**Comment by shadowwalkersb** [comment]
Can it be fixed somehow, so it is not overwritten? I mean the `BINSTAR_TOKEN`.

**Comment by jakirkham** [comment]
Not sure. We have been discussing a different way of doing uploads actually. So that might not need a token in this sense per se. However, it is really too early to tell how that will shake out.

Maybe another thought is have the linter webservice check for changes like this in PRs and note changes to tokens like this. That would at least warn us that something is up and to look more closely.

**Comment by shadowwalkersb** [comment]
Linter idea sounds good.

**Comment by shadowwalkersb** [comment]
Or, the token could be stored in a file. Just like how `conda-smithy` reads them when run locally. `conda-forge.yml` is not quite the right place to store tokens. It is for settings kind of things.

**Comment by jakirkham** [comment]
Feel free to raise issues at [conda-smithy]( https://github.com/conda-forge/conda-smithy ) or [conda-forge-webservices]( https://github.com/conda-forge/conda-forge-webservices ) with any ideas.

**Comment by jakirkham** [comment]
Appears there are now Windows packages so closing as resolved.

**Comment by shadowwalkersb** [comment]
Great!

**Comment by shadowwalkersb** [comment]
Great!
